#!/bin/bash
BRIGHTNESS_CHANGE=100
BRIGHTNESS_PATH=/sys/class/backlight/intel_backlight/
CURR_BRIGHTNESS=$(cat "${BRIGHTNESS_PATH}brightness")
NEW_BRIGHTNESS=$(($CURR_BRIGHTNESS-$BRIGHTNESS_CHANGE))
MIN_BRIGHTNESS=$(($(cat "${BRIGHTNESS_PATH}bl_power")+1))
if [[ $NEW_BRIGHTNESS -lt $MIN_BRIGHTNESS ]]
then
  NEW_BRIGHTNESS=$MIN_BRIGHTNESS
fi
echo $NEW_BRIGHTNESS > "${BRIGHTNESS_PATH}brightness"
